### 
FROM registry.access.redhat.com/ubi8/ubi
LABEL maintainer="Sean Nelson <snelson@redhat.com>"
ARG POD_USER_NAME=build
ARG POD_USER_UID=1001
ARG POD_USER_GID=0
ARG POD_HOME_DIR=/home/build

ENV HOME="${POD_HOME_DIR}"

USER root

RUN echo "enabled=0" >> /etc/yum/pluginconf.d/subscripton-manager.conf
RUN dnf module install -y container-tools --skip-broken && \
    dnf install -y git buildah podman skopeo && \
    dnf clean all && \
    rm -rf /var/cache /var/log/dnf* /var/log/yum.*

RUN useradd ${POD_USER_NAME} --uid ${POD_USER_UID} --gid ${POD_USER_GID} --home-dir ${POD_HOME_DIR} --create-home --shel /sbin/nologin && \
    chown -R ${POD_USER_UID}:${POD_USER_GID} ${POD_HOME_DIR} && \
    chmod -R g+w ${POD_HOME_DIR}

USER ${POD_USER_UID}
