stages:
- build
- build-push
- notifications
- artifacts
- artifacts-notifications
- security

include:
  - project: gitlab-pipelines/helpers
    ref: master
    file:
      - step_tools/buildah/bud.yml
      - step_tools/podman/push.yml
      - step_tools/notifications/slack.yml

clean_varlibcontainers_pvc:
  stage: .pre
  image:
    name: quay.io/podman/stable
  inherit:
    variables: true
  variables:
    STORAGE_DRIVER: vfs
  script:
    - podman --storage-driver=$STORAGE_DRIVER rm --all --force
    - podman --storage-driver=$STORAGE_DRIVER rmi --all --force
  tags:
    - openshift

container_build_dockerfile:
  extends: .buildah_bud
  stage: build
  # inherit:
  #   variables: true
  variables:
    TARGET: $UNTRUSTED_IMAGE_TARGET

container_build_push_image:
  extends: .podman_push
  stage: build-push
  # inherit:
  #   variables: true
  variables:
    TARGET: $UNTRUSTED_IMAGE_TARGET

container_build_notification:
  extends: .send_slack_notification
  stage: notifications
  # inherit:
  #   variables: true
  variables:
    MESSAGE: "Container Build Complete"
