stages:
- pull
- scan
- notifications
- retag
- push
- deploy

include:
  - project: gitlab-pipelines/helpers
    ref: master
    file:
      - step_tools/notifications/slack.yml
      - step_tools/clair/scan.yml
      - step_tools/podman/pull.yml
      - step_tools/podman/push.yml
      - step_tools/skopeo/copy.yml
      - step_tools/twistlock/scan.yml

pull_image:
  extends: .podman_pull
  stage: pull
  inherit:
    variables: true
  variables:
    TARGET: $UNTRUSTED_IMAGE_TARGET

clair_scanner:
  extends: .clair_scan
  stage: scan
  needs: [pull_image]
  inherit:
    variables: true
  variables:
    TARGET: $UNTRUSTED_IMAGE_TARGET

twistlock_scan:
  extends: .twistlock_scan
  stage: scan
  needs: [pull_image]
  inherit:
    variables: true
  variables:
    TARGET: $UNTRUSTED_IMAGE_TARGET

report_clair_results:
  extends: .send_slack_notification
  stage: notifications
  needs: [clair_scanner]
  inherit:
    variables: true
  variables:
    MESSAGE: "Clair Results"

report_twistlock_results:
  extends: .send_slack_notification
  stage: notifications
  needs: [twistlock_scan]
  inherit:
    variables: true
  variables:
    MESSAGE: "Twistlock Results"

retag_and_push_container:
  extends: .skopeo_copy
  stage: retag
  inherit:
    variables: true
  variables:
    SRC_IMAGE: docker://$UNTRUSTED_IMAGE_TARGET
    DEST_IMAGE: docker://$TRUSTED_IMAGE_TARGET

# push_to_quay:
#   extends: .podman_push
#   stage: push
#   inherit:
#     variables: true
#   variables:
#     TARGET: $TRUSTED_IMAGE_TARGET

# trigger_deployment_dev:
#   stage: deploy
#   inherit:
#     variables: true
#   variables:
#     ENVIRONMENT: dev
#     CLUSTER: ocp4.example.com
#     IMAGE: something
#   trigger:
#     strategy: depend
#     include:
#       - project: gitlab-pipeline/pipelines
#         ref: master
#         file: /environment-deployment/.gitlab-ci.yml
#   tags:
#     - openshift
