stages:
- build
- build-push
- notifications
- artifacts
- artifacts-notifications
- security

# variables:
#   TLSVERIFY:
#     value: "false"
#     description: "TLS Certificate Verification. If there are x509 errors, try using 'false', but it's Best Practice to fix your certificates!"
#   UNTRUSTED_IMAGE_TARGET:
#     value: "$CI_REGISTRY_IMAGE:untrusted-$CI_COMMIT_REF_SLUG"
#     description: "The Untrusted Container Image Location"
#   TRUSTED_IMAGE_TARGET:
#     value: "$CI_REGISTRY_IMAGE:trusted-$CI_COMMIT_REF_SLUG"
#     description: "The Trusted Container Image Location."

# variables:
#   TLSVERIFY: "false"
#   UNTRUSTED_IMAGE_TARGET: $CI_REGISTRY_IMAGE:untrusted-$CI_COMMIT_REF_SLUG
#   TRUSTED_IMAGE_TARGET: $CI_REGISTRY_IMAGE:trusted-$CI_COMMIT_REF_SLUG

include:
  - project: gitlab-pipelines/helpers
    file:
      - processes/buildah/bud.yml
      - processes/podman/push.yml
      - processes/notifications/slack.yml

clean_varlibcontainers_pvc:
  stage: .pre
  image:
    name: quay.io/podman/stable
  inherit:
    variables: true
  variables:
    STORAGE_DRIVER: vfs
  script:
    - podman --storage-driver=$STORAGE_DRIVER rm --all --force
    - podman --storage-driver=$STORAGE_DRIVER rmi --all --force

container_build_dockerfile:
  extends: .buildah_bud
  stage: build
  inherit:
    variables: true
  variables:
    TARGET: $UNTRUSTED_IMAGE_TARGET

container_build_push_image:
  extends: .podman_push
  stage: build-push
  # needs: [container_build_dockerfile]
  inherit:
    variables: true
  variables:
    TARGET: $UNTRUSTED_IMAGE_TARGET

# container_build_notification:
#   extends: .send_slack_notification
#   stage: notifications
#   inherit:
#     variables: true
#   variables:
#     MESSAGE: "Container Build Complete"

trigger_container_security:
  stage: security
  inherit:
    variables: true
  # variables:
  #   TLSVERIFY: 'false'
  #   SOURCE_CONTAINER_IMAGE: quay.apps.ocp4.example.com/untrusted/$CI_PROJECT_NAME:untrusted-$CI_COMMIT_SHORT_SHA
  #   DEST_CONTAINER_IMAGE: quay.apps.ocp4.example.com/trusted/$CI_PROJECT_NAME:untrusted-$CI_COMMIT_SHORT_SHA
  trigger:
    strategy: depend
    include:
      - project: gitlab-pipelines/pipelines
        file: /container-security.yml
