stages:
  - notifications
  - trigger-container-build
  - trigger-container-security

variables:
  TLSVERIFY: 'false'
  DOCKERFILE: "Containerfile"
  UNTRUSTED_IMAGE_TARGET: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-untrusted
  TRUSTED_IMAGE_TARGET: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-trusted

include:
  - project: gitlab-pipelines/helpers
    file:
      - step_tools/notifications/slack.yml

container_build_notification:
  extends: .send_slack_notification
  stage: notifications
  inherit:
    variables: true
  variables:
    MESSAGE: "Container Build Started"

trigger_container_build:
  stage: trigger-container-build
  inherit:
    variables: true
  trigger:
      strategy: depend
      include:
          - project: gitlab-pipelines/pipelines
            file: /container-build.yml

trigger_container_security:
  stage: trigger-container-security
  inherit:
    variables: true
  trigger:
      strategy: depend
      include:
          - project: gitlab-pipelines/pipelines
            file: /container-security.yml
