stages:
  - trigger-next

variables:
  TLSVERIFY: 'false'
  DOCKERFILE: "Containerfile"

trigger_container_build:
    stage: trigger-next
    inherit:
      variables: true
    trigger:
        strategy: depend
        include:
            - project: gitlab-pipelines/pipelines
              file: /container-build.yml

