namespace: example
name: slack
version: 1.0.0
readme: README.adoc

authors:
- Sean Nelson <snelson@redhat.com>

description: Skeleton for a collection

license:
- GPL-2.0-or-later
license_file: ''

tags: []
dependencies: {}

repository: https://gitlab.developer.hkn.lab/gitlab-pipelines/ansible/collection_template
documentation: http://pages.developer.hkn.lab/gitlab-pipelines/ansible/collection_template
homepage: https://gitlab.developer.hkn.lab/gitlab-pipelines/ansible/collection_template
