.python_coverage: &python_coverage
  image:
    - name: python-38
  inherit:
    variables: true
  script:
    - python coverage command

.python_lint: &python_lint
  image:
    - name: python-38
  inherit:
    variables: true
  script:
    - pylint

.python_tox: &python_tox
  image:
    - name: python-38
  inherit:
    variables: true
  script:
    - tox .
