.python_coverage: &python_coverage
  image: python-38
  # variables:
  script:
    - python coverage command

.python_lint: &python_lint
  image:
    - name: python-38
  # variables:
  script:
    - pylint

.python_tox: &python_tox
  image:
    - name: python-38
  script:
    - tox .
